services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    
    Echtermax\PartyBundle\:
        resource: '../../'
        exclude: '../../{Entity,Resources,Tests}'
    
    Echtermax\PartyBundle\EventListener\DataContainer\PartyCallbackListener:
        public: true
        arguments:
            - '@contao.framework'
